### ISSUE TITLE
Timing leak in powMod

### ISSUE THREAD

**Issue by soatok** [paulmillr/noble-ed25519#13]
From [the blog post](https://paulmillr.com/posts/noble-secp256k1-fast-ecc/), you correctly noted that "[t]he best we can do is an algorithmic constant-time".

However, the `powMod()` implementation isn't algorithmic constant-time:

https://github.com/paulmillr/noble-ed25519/blob/c7a621d68e4181e5e5e23bd2286dfcc319954ca5/index.js#L438-L440

The lowest bit of `power` determines [whether a branch gets executed](https://github.com/veorq/cryptocoding#avoid-branchings-controlled-by-secret-data), and the branch where it does contains an extra function call.

The simplest workaround is to use a [constant-time conditional select](https://soatok.blog/2020/08/27/soatoks-guide-to-side-channel-attacks/#conditional-select).

For example (not tested):

```typescript
function powMod(a, power, m = CURVE.P) {
    let res = 1n;
    while (power > 0n) {
        res = conditionalSelect(power & 1n, mod(res * a, m), res);
        power >>= 1n;
        a = mod(a * a, m);
    }
    return res;
}
function conditionalSelect(swap, left, right) {
    mask = -(swap & 1n);
    return right ^ ((left ^ right) & mask);
}
```

This sort of design pattern only works with functions, not macros (e.g. C compiler directives).

----

Wanted to clarify: This isn't just leaking the *magnitude* of `power`, but the actual bit pattern.

**Comment by paulmillr** [comment]
Thanks for auditing the code.

`powMod` is unsafe, because it's used in `fromRistrettoBytes`, which decodes a byte-string `s_bytes` representing a compressed Ristretto point into extended coordinates. It's basically a conversion.

It is different from `fromRistrettoHash`, which applies Elligator twice. 

Now, the question here is: do we need constant-timeness in `fromRistrettoBytes`?

As an optimization, i'm already using `multiplyUnsafe` in `verify()`. The reason for this is that `verify` doesn't work with private data, and speed gains from it are massive, like 1.5-2x.

**Comment by soatok** [comment]
I thought you were using it in more places, but that turns out to be a separate `powMod2()` function.

https://github.com/paulmillr/noble-ed25519/blob/ec60640bce14aac5b903d7fb6c4615f946a96be3/index.js#L493-L501

Timing leaks in integer multiplication (which are [unfortunately common](https://bearssl.org/ctmul.html)) and modulo operators are probably out of scope, since that's internal to the engine implementation for the `bigint` type.

**Comment by paulmillr** [comment]
Alright. Does this mean we could close the issue?

**Comment by soatok** [comment]
I believe so. If someone else reports something similar *but with stronger arguments*, feel free to revisit and I'll chime in.
